APP_NAME = "BarbechAI"
APP_VERSION = "1.0.0"

SUPPORTED_COUNTRY = "Tunisia"

DEFAULT_BUSINESS_TYPE = "restaurant"

LEAD_STATUSES = [
    "NEW",
    "ENRICHING",
    "ENRICHED",
    "CONTACTED",
    "QUALIFIED",
    "WON",
    "LOST",
]

SOURCE_OSM = "osm"
SOURCE_FOURSQUARE = "foursquare"
SOURCE_DUCKDUCKGO = "duckduckgo"
SOURCE_PAGESJAUNES = "pagesjaunes"
SOURCE_HERE = "here"

MAX_SEARCH_RESULTS = 500
MAX_ENRICHMENT_WORKERS = 4

DEFAULT_REQUEST_TIMEOUT = 10

DEFAULT_USER_AGENT = "BarbechAI/1.0"
